org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=warpload
mod_name=WarpLoad
mod_license=LGPL-3.0
mod_version=1.1.7
mod_group_id=com.warpload
mod_authors=MineRealmsPowered. Based on Lightspeed by CCr4ft3r & kltyton (LGPL-3.0) and OptiLoad by NeoFastFTL.
mod_description=Ultimate startup accelerator for heavy modpacks. Merges persistent resource-path indexes, disk-reload caches, zip-datapack extraction, parallel JSON loading, model baking cache and server AI gating into one mod.
